name: KakaoCloud Container Registry Test 

on:
  push:
    branches:
      - test
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Kakao Cloud Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.KAKAO_CLOUD_PROJECT_NAME }}.kr-central-2.kcr.dev
        username: ${{ secrets.KAKAO_CLOUD_ACCESS_KEY }}
        password: ${{ secrets.KAKAO_CLOUD_ACCESS_SECRET_KEY }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.KAKAO_CLOUD_PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.KAKAO_CLOUD_REPOSITORY_NAME }}/image_name:latest
