name: KakaoCloud-handson
run-name: KakaoCloud handson workflow
on: [push]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Login KakaoCloud
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.KAKAO_CLOUD_PROJECT_NAME }}.kr-central-2.kcr.dev
        username: ${{ secrets.KAKAO_CLOUD_ACCESS_KEY }}
        password: ${{ secrets.KAKAO_CLOUD_ACCESS_SECRET_KEY }}

    - name: Set ENV and Build/Push
      run: |
        echo "TIME=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
        echo ${{env.TIME}}